# Generated by Django 5.2.4 on 2025-12-25 15:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=core.models.sanitize_filename),
        ),
    ]
